markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: Data Science 
    description: Personal Knowledge Management
    title: Walking on my way 
    url: http://chrispher.github.io 
    duoshuo: chrispher2012
    tongji: chrispher2012 
author:
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: http://weibo.com/u/2917650677
    github: https://github.com/chrispher
    logo:                                                # logo地址
