markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 12
paginate_path: page/:num

blog:
    name: chrispher
    description: Data Science
    title: Data Science
    url: http://chrispher.github.com 
    duoshuo: chrispher2012
author:
    # Profile links on the left sidebar, leave blank to ignore
    name: chrispher guan 
    email: chrispher2012@gmail.com 
    weibo: 2917650677  # weibo ID
    github: chrispher  # github ID
    linkedin: chrispher-guan/5a/a68/6b8
    logo: http://chrispher.github.com/res/img/logo.png

